CC      	= gcc
CFLAGS  	= -Wall
FILES		= use_linked_list.c linked_list.c
OBJFILES	= use_linked_list.o linked_list.o
COMP		= a7_p3

all: main

# Compile from source files
main: $(FILES)
	$(CC) $(CFLAGS) -o $(COMP) $(FILES)

# Compile only the object file of the functions definition file
linked_list.o: linked_list.c
	$(CC) $(CFLAGS) -c linked_list.c

# Compile only the object file of the main function file
use_linked_list.o: use_linked_list.c
	$(CC) $(CFLAGS) -c use_linked_list.c

# Target to compile both targets linked_list.o and use_linked_list.o
compile_only: linked_list.o use_linked_list.o

# Target to link the object files together
link_only: linked_list.o use_linked_list.o
	$(CC) -o $(COMP) $(OBJFILES)

# Delete only the .o files using the wildcard pattern
delete_objects:
	rm -f *.o 

# Delete only the executable file 
delete_exe:
	rm -f $(COMP)

# Target to delete all object files and the executable file
delete_all: delete_exe delete_objects